openapi: 3.0.0
info:
  title: Fence OpenAPI Specification admin/user core metadata API
  version: 0.1.0
  description: Access management for Gen3 data commons. Code is available on [GitHub](https://github.com/uc-cdis/fence).
  termsOfService: http://cdis.uchicago.edu/terms/
  contact:
    email: cdis@uchicago.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://example.domain/
tags:
- name: core metadata
paths:
  /{object_id}:
    get:
      summary: Get core metadata for an object_id
      tags:
      - core metadata
      parameters:
      - name: object_id
        in: path
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        schema:
          type: string
          enum:
          - application/json (default)
          - x-bibtex
          - application/vnd.schemaorg.ld+json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                object_id: 123
                file_name: my-file.txt
                data_format: TXT
                file_size: 10
            application/vnd.schemaorg.ld+json:
              schema:
                type: object
              example:
                '@context': http://schema.org
                '@type': Dataset
                '@id': https://dataguids.org/index/123
                identifier:
                - '@type': PropertyValue
                  propertyID: dataguid
                  value: '123'
                - '@type': PropertyValue
                  propertyID: md5
                  value: bc575394b5565a1d3fa20abe2b132896
                publisher:
                  '@type': Organization
                  name: my-org
                author:
                  name: my-author
                description: my-description
                additionalType: submitted_aligned_reads
                name: my-file.txt
                datePublished: 2019-01-24 19:40:02.537991+00:00
            x-bibtex:
              schema:
                type: string
              example: '@misc {123, file_name = "my-file.txt", data_format = "TXT", file_size = "10", object_id = "123"}'
        '401':
          description: Authentication error
        '404':
          description: No core metadata was found for this object_id
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          scopes:
            user: generic user access
