openapi: 3.0.0
info:
  title: Fence OpenAPI Specification admin/user credentials API
  version: 0.1.0
  description: Access management for Gen3 data commons. Code is available on [GitHub](https://github.com/uc-cdis/fence).
  termsOfService: http://cdis.uchicago.edu/terms/
  contact:
    email: cdis@uchicago.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://example.domain/
tags:
- name: credentials
  description: Access credentials
paths:
  /credentials:
    get:
      tags:
      - credentials
      summary: List credential resources
      description: List different resources user can have credentials
      security:
      - OAuth2:
        - user
      operationId: listSources
      responses:
        '200':
          description: successful operation
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          scopes:
            user: generic user access
